### ISSUE TITLE
Allow usage of existing FD file for different table

### ISSUE THREAD

**Issue by PaulVII** [SchweizerischeBundesbahnen/BCNFStar#303]
As a user, I want to be able to use existing metanome results for new tables, so I can skip the waiting time if I know that the data is identical.
Furthermore, it would be nice if all files that are valid even after persisting would be added to the index file automatically.

**Comment by janina-adamcic** [comment]
Duplicate https://github.com/SchweizerischeBundesbahnen/BCNFStar/issues/230
